import {
  mysqlTable,
  int,
  varchar,
  text,
  boolean,
  decimal,
  timestamp,
  date,
  json,
  index,
  unique,
} from 'drizzle-orm/mysql-core';
import { users } from './schema';

/**
 * Schema do Módulo de Metas
 * Sistema de cronograma dinâmico com revisão espaçada
 */

/**
 * Planos de Estudo
 * Configuração do cronograma do aluno
 */
export const planosEstudo = mysqlTable(
  'metas_planos_estudo',
  {
    id: varchar('id', { length: 36 }).primaryKey(),
    usuarioId: varchar('usuario_id', { length: 36 })
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    titulo: varchar('titulo', { length: 255 }).notNull(),
    descricao: text('descricao'),
    
    // Configuração de tempo
    horasPorDia: decimal('horas_por_dia', { precision: 4, scale: 2 }).notNull(),
    diasDisponiveisBitmask: int('dias_disponiveis_bitmask').notNull().default(31), // Seg-Sex = 31
    
    // Datas (UTC)
    dataInicio: date('data_inicio').notNull(),
    dataFim: date('data_fim'),
    
    // Status
    status: varchar('status', { length: 20 }).notNull().default('ativo'), // ativo, pausado, concluido
    
    // Auditoria
    criadoPorId: varchar('criado_por_id', { length: 36 })
      .notNull()
      .references(() => users.id),
    criadoEm: timestamp('criado_em').notNull().defaultNow(),
    atualizadoEm: timestamp('atualizado_em').notNull().defaultNow().onUpdateNow(),
  },
  (table) => ({
    usuarioIdx: index('idx_planos_usuario').on(table.usuarioId),
    statusIdx: index('idx_planos_status').on(table.status),
  })
);

/**
 * Metas (Unidades de Estudo)
 * Cada meta representa uma sessão de estudo específica
 */
export const metas = mysqlTable(
  'metas_cronograma',
  {
    id: varchar('id', { length: 36 }).primaryKey(),
    planoId: varchar('plano_id', { length: 36 })
      .notNull()
      .references(() => planosEstudo.id, { onDelete: 'cascade' }),
    
    // Numeração única e ordenável
    metaNumberBase: int('meta_number_base').notNull(),
    metaNumberSuffix: int('meta_number_suffix'),
    displayNumber: varchar('display_number', { length: 20 }).notNull(), // "#015.1"
    orderKey: varchar('order_key', { length: 20 }).notNull(), // "000015/0001"
    
    // KTree (fonte de verdade) - Referências para disciplina/assunto
    // Nota: Assumindo que ktree_nodes será criado posteriormente
    ktreeDisciplinaId: varchar('ktree_disciplina_id', { length: 36 }).notNull(),
    ktreeAssuntoId: varchar('ktree_assunto_id', { length: 36 }).notNull(),
    ktreeTopicoId: varchar('ktree_topico_id', { length: 36 }),
    ktreeSubtopicoId: varchar('ktree_subtopico_id', { length: 36 }),
    
    // Tipo e categoria
    tipo: varchar('tipo', { length: 20 }).notNull(), // ESTUDO, QUESTOES, REVISAO
    incidencia: varchar('incidencia', { length: 20 }).default('NA'), // ALTA, MEDIA, BAIXA, NA
    
    // Duração
    duracaoPlanejadaMin: int('duracao_planejada_min').notNull(),
    duracaoRealSec: int('duracao_real_sec').default(0),
    
    // Agendamento
    scheduledDate: date('scheduled_date').notNull(),
    scheduledOrder: int('scheduled_order').notNull(), // Ordem dentro do dia
    scheduledAtUtc: timestamp('scheduled_at_utc'), // Para metas fixas com horário específico
    
    // Status
    status: varchar('status', { length: 30 }).notNull().default('PENDENTE'),
    // PENDENTE, EM_ANDAMENTO, CONCLUIDA, PRECISA_MAIS_TEMPO
    concludedAtUtc: timestamp('concluded_at_utc'),
    
    // Conteúdo
    orientacoesEstudo: text('orientacoes_estudo'),
    
    // Metas fixas
    fixed: boolean('fixed').default(false),
    fixedRuleJson: json('fixed_rule_json'), // { "diasSemana": ["segunda"], "horario": "PRIMEIRO" }
    
    // Automação
    autoGenerated: boolean('auto_generated').default(false),
    parentMetaId: varchar('parent_meta_id', { length: 36 }),
    
    // Revisão espaçada
    reviewConfigJson: json('review_config_json'), // { "numeroRevisao": 1, "diasAposEstudo": 3 }
    
    // Sequenciamento (para "preciso de mais tempo")
    sequenceLabel: varchar('sequence_label', { length: 10 }), // "2/2", "3/3"
    originalMetaId: varchar('original_meta_id', { length: 36 }),
    
    // Omissão (soft delete)
    omitted: boolean('omitted').default(false),
    omissionReason: varchar('omission_reason', { length: 50 }),
    omittedAt: timestamp('omitted_at'),
    
    // Hash para idempotência de batch
    rowHash: varchar('row_hash', { length: 64 }),
    
    // Auditoria
    criadoPorId: varchar('criado_por_id', { length: 36 })
      .notNull()
      .references(() => users.id),
    criadoEm: timestamp('criado_em').notNull().defaultNow(),
    atualizadoEm: timestamp('atualizado_em').notNull().defaultNow().onUpdateNow(),
  },
  (table) => ({
    planoScheduleIdx: index('idx_metas_plan_schedule').on(
      table.planoId,
      table.scheduledDate,
      table.scheduledOrder
    ),
    planoStatusIdx: index('idx_metas_plan_status').on(
      table.planoId,
      table.status,
      table.omitted
    ),
    planoOrderIdx: index('idx_metas_plan_order').on(table.planoId, table.orderKey),
    parentIdx: index('idx_metas_parent').on(table.parentMetaId),
    concludedIdx: index('idx_metas_concluded').on(table.concludedAtUtc),
    displayNumberUnique: unique('unique_display_number').on(table.planoId, table.displayNumber),
    orderKeyUnique: unique('unique_order_key').on(table.planoId, table.orderKey),
  })
);

/**
 * Materiais de Estudo
 * PDFs, vídeos, links, áudios
 */
export const materiais = mysqlTable('materiais', {
  id: varchar('id', { length: 36 }).primaryKey(),
  tipo: varchar('tipo', { length: 20 }).notNull(), // PDF, VIDEO, LINK, AUDIO
  titulo: varchar('titulo', { length: 255 }).notNull(),
  url: text('url').notNull(),
  ownerId: varchar('owner_id', { length: 36 })
    .notNull()
    .references(() => users.id),
  criadoEm: timestamp('criado_em').notNull().defaultNow(),
});

/**
 * Questões
 * Banco de questões para prática
 */
export const questoes = mysqlTable('questoes', {
  id: varchar('id', { length: 36 }).primaryKey(),
  fonte: varchar('fonte', { length: 100 }),
  referenciaExterna: varchar('referencia_externa', { length: 100 }),
  disciplinaId: varchar('disciplina_id', { length: 36 }),
  assuntoId: varchar('assunto_id', { length: 36 }),
  textoQuestao: text('texto_questao').notNull(),
  criadoEm: timestamp('criado_em').notNull().defaultNow(),
});

/**
 * Relacionamento: Metas ↔ Materiais
 */
export const metasMateriais = mysqlTable(
  'metas_cronograma_materiais',
  {
    id: varchar('id', { length: 36 }).primaryKey(),
    metaId: varchar('meta_id', { length: 36 })
      .notNull()
      .references(() => metas.id, { onDelete: 'cascade' }),
    materialId: varchar('material_id', { length: 36 })
      .notNull()
      .references(() => materiais.id, { onDelete: 'cascade' }),
    criadoEm: timestamp('criado_em').notNull().defaultNow(),
  },
  (table) => ({
    metaMaterialUnique: unique('unique_meta_material').on(table.metaId, table.materialId),
  })
);

/**
 * Relacionamento: Metas ↔ Questões
 */
export const metasQuestoes = mysqlTable(
  'metas_cronograma_questoes',
  {
    id: varchar('id', { length: 36 }).primaryKey(),
    metaId: varchar('meta_id', { length: 36 })
      .notNull()
      .references(() => metas.id, { onDelete: 'cascade' }),
    questaoId: varchar('questao_id', { length: 36 })
      .notNull()
      .references(() => questoes.id, { onDelete: 'cascade' }),
    criadoEm: timestamp('criado_em').notNull().defaultNow(),
  },
  (table) => ({
    metaQuestaoUnique: unique('unique_meta_questao').on(table.metaId, table.questaoId),
  })
);

/**
 * Logs de Auditoria
 * Rastreamento de todas as mudanças
 */
export const auditLogs = mysqlTable(
  'audit_logs',
  {
    id: varchar('id', { length: 36 }).primaryKey(),
    actorId: varchar('actor_id', { length: 36 })
      .notNull()
      .references(() => users.id),
    action: varchar('action', { length: 50 }).notNull(), // create, update, delete, redistribute
    entity: varchar('entity', { length: 50 }).notNull(), // meta, plan, ktree_node
    entityId: varchar('entity_id', { length: 36 }).notNull(),
    beforeJson: json('before_json'),
    afterJson: json('after_json'),
    metadata: json('metadata'), // Informações contextuais
    criadoEm: timestamp('criado_em').notNull().defaultNow(),
  },
  (table) => ({
    entityIdx: index('idx_audit_entity').on(table.entity, table.entityId),
    actorIdx: index('idx_audit_actor').on(table.actorId),
    createdIdx: index('idx_audit_created').on(table.criadoEm),
  })
);

/**
 * Batch Imports
 * Controle de importações em lote
 */
export const metasBatchImports = mysqlTable('metas_batch_imports', {
  id: varchar('id', { length: 36 }).primaryKey(),
  planoId: varchar('plano_id', { length: 36 })
    .notNull()
    .references(() => planosEstudo.id, { onDelete: 'cascade' }),
  fileName: varchar('file_name', { length: 255 }).notNull(),
  totalRows: int('total_rows').notNull(),
  createdCount: int('created_count').notNull(),
  duplicatedCount: int('duplicated_count').notNull(),
  invalidCount: int('invalid_count').notNull(),
  errors: json('errors'), // Array de erros
  uploadedById: varchar('uploaded_by_id', { length: 36 })
    .notNull()
    .references(() => users.id),
  criadoEm: timestamp('criado_em').notNull().defaultNow(),
});

// Tipos TypeScript inferidos
export type PlanoEstudo = typeof planosEstudo.$inferSelect;
export type InsertPlanoEstudo = typeof planosEstudo.$inferInsert;

export type Meta = typeof metas.$inferSelect;
export type InsertMeta = typeof metas.$inferInsert;

export type Material = typeof materiais.$inferSelect;
export type InsertMaterial = typeof materiais.$inferInsert;

export type Questao = typeof questoes.$inferSelect;
export type InsertQuestao = typeof questoes.$inferInsert;

export type AuditLog = typeof auditLogs.$inferSelect;
export type InsertAuditLog = typeof auditLogs.$inferInsert;

export type MetaBatchImport = typeof metasBatchImports.$inferSelect;
export type InsertMetaBatchImport = typeof metasBatchImports.$inferInsert;
